# Generated by Django 5.1.2 on 2024-11-18 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(condition=models.Q(('deleted_at', None)), fields=['deleted_at'], name='indexing_undeleted_fields'),
        ),
    ]
