# Generated by Django 5.1.2 on 2024-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_field_options_field_indexing_undeleted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
