# Generated by Django 5.1.2 on 2025-01-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0004_rename_mesure_field_measure_remove_field_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="equipements",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="ground_ph",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="ground_type",
            field=models.CharField(
                choices=[
                    ("C", "Clayey"),
                    ("L", "Loamy"),
                    ("S", "Sandy"),
                    ("CL", "Clayey_Loamy"),
                ],
                default="C",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="field",
            name="lat",
            field=models.DecimalField(
                decimal_places=10, default=1114447, max_digits=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="field",
            name="long",
            field=models.DecimalField(
                decimal_places=10, default=8855222, max_digits=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="field",
            name="organic_materials",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="period",
            field=models.CharField(
                choices=[
                    ("SP", "Spring"),
                    ("WI", "Winter"),
                    ("SU", "Summer"),
                    ("AU", "Autumn"),
                ],
                max_length=2,
            ),
        ),
    ]
