# Generated by Django 5.1.2 on 2025-01-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0007_field_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="prod_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
