# Generated by Django 5.1.2 on 2025-01-22 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0008_field_prod_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_name', models.CharField(max_length=120)),
                ('product_type', models.CharField(max_length=120)),
                ('product_country', models.CharField(max_length=50)),
                ('product_region', models.CharField(max_length=120)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_measurement_unit', models.CharField(choices=[('Kg', 'Kilogram'), ('T', 'Tonne')], default='Kg', max_length=3)),
                ('product_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('product_on_sale', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.field')),
            ],
        ),
    ]
