# Generated by Django 5.1.2 on 2024-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(db_index=True, max_length=200, unique=True),
        ),
    ]
