# Generated by Django 5.1.2 on 2024-11-19 13:34

import django.core.validators
import plants.apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(6), plants.apps.core.validators.special_characters_check], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, validators=[plants.apps.core.validators.str_checker]),
        ),
    ]
